services:
  - type: worker
    name: telegram-dice-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: 8206388608:AAFFI9o0wuUcYZ6MStW2Yi4Sf6JBw-5fmHE
